version: '3.8'
services:

  postgresql:
    container_name: postgresqldb
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blogApp
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: springboot_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/blogApp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    restart: always

volumes:
  postgres_data:




